- src/dotnet/Chat.Client/ClientDefs.cs
- src/dotnet/Chat.Contracts/IChatAuthors.cs
- src/dotnet/Chat.Contracts/IChats.cs
- src/dotnet/Chat.Service/ChatAuthors.cs
- src/dotnet/Chat.Service/Chats.Backend.cs
- src/dotnet/Chat.Service/Chats.cs
- src/dotnet/Chat.Service/Controllers/ChatAuthorsController.cs
- src/dotnet/Chat.Service/Controllers/ChatsController.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatAuthorCard.razor
- src/dotnet/Chat.UI.Blazor/Components/ContactLinks.razor
- src/dotnet/Chat.UI.Blazor/Pages/ChatPage.razor
- src/dotnet/Chat/Model/ChatAuthor.cs
- src/dotnet/Chat/Model/PeerChatExt.cs
- src/dotnet/Users.Contracts/Backend/IUserContactsBackend.cs
- src/dotnet/Users.Service/UserContactsBackend.cs
Users peer chat creation is deferred till first message posting
Short links for users peer chat: /chat/p%3Aiot6i3lpq6pk
To start conversation click on chat author avatar and in appeared card click 'Send message'
> users peer chat refactoring

- src/dotnet/UI.Blazor/Components/AccountDropdown/AccountView.razor
- src/dotnet/Users.Contracts/AuthorLikeExt.cs
- src/dotnet/Users.Contracts/UserProfile.cs
- src/dotnet/Users.Service/Db/DbUserProfileConverter.cs
- src/dotnet/Users.Service/Db/DbUserRepo.cs
- src/dotnet/Users.Service/UserAvatars.cs
- src/dotnet/Users.Service/UserProfilesBackend.cs
It was decided UserProfile should not inherit Author anymore
> chore: remove inheritance of UserProfile from Author

- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/ChatMessage.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/chat-view.css
- src/nodejs/styles/colors.css
> highlighting own messages

- src/dotnet/Chat.Contracts/IChatAuthors.cs
- src/dotnet/Chat.Service/ChatAuthors.cs
- src/dotnet/Chat.Service/Controllers/ChatAuthorsController.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatAuthors.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatHeader.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatSettingsToggle.razor
- src/dotnet/Chat.UI.Blazor/Pages/ChatPage.razor
- src/dotnet/UI.Blazor/Components/PageWithHeaderAndFooter.razor
- src/dotnet/UI.Blazor/Layouts/ChatPageLayout.razor
- src/dotnet/Users.UI.Blazor/Module/UsersBlazorUIModule.cs
- src/dotnet/Users.UI.Blazor/Services/UserSettings.cs
> feat: chat settings\participants panel

- src/dotnet/Chat.UI.Blazor/Components/ChatLinks.razor
> feat: hide default chat if no access

- src/dotnet/Chat.UI.Blazor/Components/ChatFooter.razor
- src/dotnet/Chat.UI.Blazor/Pages/ChatPage.razor
- src/dotnet/Chat.UI.Blazor/Pages/JoinChatPage.razor
code cleanup - removed unused auto-join
> chore: remove auto join

- src/dotnet/UI.Blazor/Components/PageWithHeaderAndFooter.razor
> fix: chat title is wrongly positioned

- src/dotnet/Chat.Client/ClientDefs.cs
- src/dotnet/Chat.Contracts/IChatAuthors.cs
- src/dotnet/Chat.Service/ChatAuthors.cs
- src/dotnet/Chat.Service/Controllers/ChatAuthorsController.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatAuthorBadge/ChatAuthorBadge.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatAuthorList.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel.razor
- src/dotnet/Chat.UI.Blazor/Components/InviteChatAuthor.razor
> feat: invite users from the contact list to the chat 

- Packages.props
rollbacked nbgv package to fix watch mode
> fix: watch mode

- src/dotnet/Chat.Service.Migration/Migrations/20220515201722_AddChatPicture.Designer.cs
- src/dotnet/Chat.Service.Migration/Migrations/20220515201722_AddChatPicture.cs
- src/dotnet/Chat.Service/ChatsBackend.cs
- src/dotnet/Chat.Service/Db/DbChat.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatHeader.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/ChatBasicSettings.razor
- src/dotnet/Chat/Model/Chat.cs
- src/dotnet/UI.Blazor/Components/ChatIcon/ChatIcon.razor
- src/dotnet/UI.Blazor/Components/ChatIcon/ChatIconSize.cs
- src/dotnet/UI.Blazor/Components/ChatIcon/chat-icon.css
- src/dotnet/UI.Blazor/exports.ts
> feat: chat icons

- src/dotnet/Chat.Service/Db/DbChatEntry.cs
- src/dotnet/Chat.UI.Blazor/Components/DeleteMessageModal.razor
> feat: delete message

- src/dotnet/Chat.Service/ContentSaverBackend.cs
- src/dotnet/Chat.Service/Controllers/ChatPicturesController.cs
- src/dotnet/Chat.Service/Controllers/ContentController.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/ChatBasicSettings.razor
- src/dotnet/Chat.UI.Blazor/Module/ChatBlazorUIModule.cs
- src/dotnet/Core/Blobs/Content.cs
- src/dotnet/Core/Blobs/ContentSaver.cs
- src/dotnet/Core/Blobs/IContentSaver.cs
- src/dotnet/Core/Constants.cs
- src/dotnet/Core/Module/CoreModule.cs
- src/dotnet/UI.Blazor/Components/ChatIcon/ChatIcon.razor
- src/dotnet/UI.Blazor/Components/ChatIcon/chat-icon.css
- src/dotnet/UI.Blazor/Components/SquareSize.cs
- src/dotnet/UI.Blazor/Module/BlazorUICoreModule.cs
- src/dotnet/UI.Blazor/Services/ContentUrlMapper.cs
> feat: store chat images at cloud store 

- src/dotnet/Chat.UI.Blazor/Components/ChatListNavbarWidget.razor
- src/dotnet/UI.Blazor/Components/ChatIcon/chat-icon.css
- src/dotnet/UI.Blazor/Components/Navbar/navbar.css
> feat: add chat icon to chat list

- src/nodejs/package-lock.json
- src/nodejs/package.json
- src/nodejs/tailwind.config.js
> fix: suppress hover state in mobile view

- src/dotnet/UI.Blazor/Components/Menu/menu.css
- src/dotnet/UI.Blazor/Components/Navbar/NavbarGroup.razor
- src/dotnet/UI.Blazor/Components/PageWithHeaderAndFooter.razor
> fix: iOS issues 

- src/dotnet/Users.Service/UserProfilesBackend.cs
> fix: invite users to a chat does not work

- src/dotnet/Chat.Service/ContentSaverBackend.cs
- src/dotnet/Chat.Service/Controllers/ChatPicturesController.cs
- src/dotnet/Chat.Service/Controllers/MessageController.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/AttachmentListPreview.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/ChatBasicSettings.razor
- src/dotnet/Core/Blobs/ContentSaver.cs
- src/dotnet/Core/Blobs/IContentSaver.cs
- src/dotnet/Core/Constants.cs
- src/dotnet/Core/FileSizeFormatter.cs
- src/dotnet/UI.Blazor/Components/ChatIcon/ChatIcon.razor
- src/dotnet/UI.Blazor/Components/ChatIcon/chat-icon.css
- src/dotnet/UI.Blazor/Components/FileUpload/FileUpload.razor
- src/dotnet/UI.Blazor/Components/FileUpload/Options.cs
- src/dotnet/UI.Blazor/Components/FileUpload/file-upload.ts
- src/dotnet/UI.Blazor/Components/FileUpload/options.ts
- src/dotnet/UI.Blazor/exports.ts
fixes for https://github.com/Actual-Chat/actual-chat/pull/186
> feat: move file uploading to js

- src/dotnet/Chat.Service/Controllers/MessageController.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/ChatMessageEditor.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/chat-message-editor.ts
- src/dotnet/Chat.UI.Blazor/Components/ChatView/ChatView.razor.cs
- src/dotnet/Chat.UI.Blazor/Components/UnreadMessagesSubHeader.razor
- src/dotnet/Chat.UI.Blazor/Module/ChatBlazorUIModule.cs
- src/dotnet/Chat.UI.Blazor/Services/Activity/UnreadMessages.cs
- src/dotnet/Chat.UI.Blazor/Services/ChatUI.State.cs
- src/dotnet/Chat.UI.Blazor/Services/ChatUI.cs
- src/dotnet/UI.Blazor/Services/PersistentState.cs
- src/dotnet/UI.Blazor/Services/PersistentStateLease.cs
- src/dotnet/UI.Blazor/Services/PersistentStateReplica.cs
- src/dotnet/UI.Blazor/Services/StateFactoryExt.cs
Related to #218 
Resolves #211
> feat: persistent mutable state

- src/dotnet/Chat.UI.Blazor/Components/ChatRecorderToggle.razor
- src/dotnet/Host/Pages/_Host.cshtml
- src/dotnet/UI.Blazor/Components/Button/ButtonSquare.razor
- src/dotnet/UI.Blazor/Components/Button/button.css
- src/dotnet/UI.Blazor/EventHandlers.cs
- src/nodejs/index.ts
- src/nodejs/package-lock.json
- src/nodejs/package.json
> feat: "Push to talk" mode

- tests/Audio.IntegrationTests/AudioProcessorTest.cs
- tests/Chat.IntegrationTests/ChatActivityTest.cs
- tests/Chat.IntegrationTests/ChatAuthorsTest.cs
- tests/Chat.IntegrationTests/ChatEntryReaderTest.cs
- tests/Chat.UI.Blazor.IntegrationTests/ChatPageAuthorizationTest.cs
- tests/Testing.Host/AppHostExt.cs
- tests/Testing.Host/AppHostTestBase.cs
- tests/Testing.Host/TestHostFactory.cs
- tests/Testing.Host/TestOutputHelperExt.cs
- tests/Testing/Collections/AppHostTests.cs
- tests/Testing/testsettings.json
- tests/UI.Blazor.IntegrationTests/ExampleTest.cs
- tests/UI.Blazor.IntegrationTests/PlaywrightTest.cs
- tests/Users.IntegrationTests/AdminGrantTest.cs
- tests/Users.IntegrationTests/SetupSessionTest.cs
- tests/Users.IntegrationTests/UserProfileAutoProvisionTest.cs
- tests/Users.IntegrationTests/UserStatusTest.cs
- tests/template.xunit.runner.json
> feat: db per integration test #237

- src/dotnet/Audio.UI.Blazor/Components/AudioRecorder/AudioRecorder.cs
- src/dotnet/Audio.UI.Blazor/Components/AudioRecorder/audio-recorder.ts
- src/dotnet/Chat.UI.Blazor/Components/ChatRecorderToggle.razor
> feat: disable record button if mic is not available

- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/ActiveReply.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/ChatView.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/ChatView.razor.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/ChatMessage.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/ChatMessageModel.cs
- src/dotnet/Chat.UI.Blazor/Components/DeleteMessageModal.razor
- src/dotnet/Chat.UI.Blazor/Services/ChatEntryReader.cs
Refactored chat data load logic so that every ChatMessage loads required data on demand instead of loading all required data for whole list.
> chore: loading data right from ChatMessage #254

- src/dotnet/Chat.UI.Blazor/Components/ChatHeader.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatLanguageToggle.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/ChatMessageEditor.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/chat-message-editor.css
- src/dotnet/Chat.UI.Blazor/Components/ChatRecorderToggle.razor
- src/dotnet/Chat.UI.Blazor/Components/RecorderPanel/RecorderPanel.razor
- src/nodejs/styles/colors.css
- src/nodejs/tailwind.config.js
> recorder panel is done, update mobile view

- src/dotnet/Chat.UI.Blazor/Components/ChatView/ChatView.razor.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/ChatMessage.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/MessageContextMenu.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Quote.razor
- src/dotnet/Chat.UI.Blazor/Components/MarkupParts/UrlMarkupView.razor
- src/dotnet/Chat.UI.Blazor/Pages/ChatPage.razor
- src/dotnet/Chat.UI.Blazor/Services/ChatUI.cs
- src/dotnet/Chat.UI.Blazor/Services/ChatUIStateSync.cs
> feat: message link / navigate to message

- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/ChatMessageEditor.razor
> fix: text stays after send

- src/nodejs/fonts/Humanist521BT.ttf
- src/nodejs/fonts/humanist.css
- src/nodejs/index.ts
- src/nodejs/styles/main.css
> feat: change default font

- src/dotnet/UI.Blazor/Components/Form/toggle.css
- src/nodejs/styles/colors.css
- src/nodejs/tailwind.config.js
> fix: toggle has the same color as hover

- src/dotnet/UI.Blazor/Components/SideNav/side-nav.css
> feat: increase right panel size

- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/RightPanelHeader.razor
- src/dotnet/UI.Blazor/Components/Button/ButtonRound.razor
- src/dotnet/UI.Blazor/Components/Tooltip/Tooltip.razor
- src/dotnet/UI.Blazor/Components/Tooltip/tooltip.css
- src/dotnet/UI.Blazor/Components/Tooltip/tooltip.ts
- src/dotnet/UI.Blazor/exports.ts
- src/nodejs/package-lock.json
- src/nodejs/package.json
> feat: add tooltip

- src/dotnet/Audio.Service/AudioProcessor.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatMenu/ChatMenuContent.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatNavbarItem.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/ChatMessage.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/MessageMenu/MessageMenuContent.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatsTab.razor
- tests/Audio.IntegrationTests/AudioProcessorTest.cs
Hide record/replay actions in menus for read-only chats.
Check write permission on recording audio message.
> Feat: read only chat actions

- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/ChatAuthors.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/ChatRightPanel.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/RightPanelChatInfo.razor
- src/dotnet/Chat.UI.Blazor/Components/components.css
- src/dotnet/UI.Blazor/Components/TabPanel/tab.css
> fix: right panel scrollbar issue

- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/ChatMessage.razor
> fix: image attachment is wrongly positioned

- src/dotnet/Chat.UI.Blazor/Components/ChatListNavbarWidget.razor
> fix: chats list scroll issue

- src/dotnet/Chat.UI.Blazor/Components/MentionList/MentionList.razor
> fix: avatar image is broken on mentions list

- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/ChatMessageEditor.razor
- src/dotnet/UI.Blazor.App/App.razor
- src/dotnet/UI.Blazor/Components/LayoutTypeProvider/ILayoutTypeProviderBackend.cs
- src/dotnet/UI.Blazor/Components/LayoutTypeProvider/LayoutType.cs
- src/dotnet/UI.Blazor/Components/LayoutTypeProvider/LayoutTypeProvider.razor
- src/dotnet/UI.Blazor/Components/LayoutTypeProvider/LayoutTypeProvider.ts
- src/dotnet/UI.Blazor/exports.ts
LayoutTypeProvider component publish cascasing property of type LayoutType.
LayoutType is enum that has 2 values: Desktop and Mobile. Value is set to Desktop  when window width >= 1024 px.
Example of usage see in ChatMessageEditor.razor.
> feat: layout type provider

- src/dotnet/Chat.UI.Blazor/Components/ChatListNavbarWidget.razor
- src/dotnet/Chat.UI.Blazor/Components/ContactListNavbarWidget.razor
> fix: no scroll on contacts list

- src/dotnet/Core/Constants.cs
> feat: increase upload image size limit

- src/dotnet/UI.Blazor/Components/ImagePreviewModal/ImagePreviewModal.razor
- src/dotnet/UI.Blazor/Components/ImagePreviewModal/image-preview-modal.css
- src/dotnet/UI.Blazor/Components/Modal/DialogFrame.razor
- src/dotnet/UI.Blazor/Components/Modal/ModalFrame.razor
> fix: unable to close image preview modal on mobile

- src/dotnet/UI.Blazor/Components/NavbarButton.razor
- src/dotnet/UI.Blazor/Components/NavbarLogo.razor
> fix: markup elements with unexpected name

- src/dotnet/UI.Blazor/Components/Button/button.css
- src/nodejs/package-lock.json
- src/nodejs/package.json
> fix: hovered elements on mobile

- src/dotnet/UI.Blazor/Components/Tooltip/tooltip.css
- src/nodejs/tailwind.config.js
> fix: menu overlaps tooltip

- src/dotnet/Chat.UI.Blazor/Components/ChatHeader.razor
- src/dotnet/Chat.UI.Blazor/Components/LeftPanel/WideLeftPanel.razor
- src/dotnet/Chat.UI.Blazor/Components/Navbar/NavbarGroupToggles.razor
> feat: remove three dots in chat header 

- src/dotnet/Chat.UI.Blazor/Components/ActiveChatRemoveButton.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatListItem.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatListListenToggle.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatListRecordingToggle.razor
- src/dotnet/Chat.UI.Blazor/Components/ContactListItem.razor
> fix: chat buttons have hover

- src/dotnet/Audio.Service/AudioHub.cs
- src/dotnet/Audio.UI.Blazor/Components/AudioRecorder/AudioRecorder.cs
- src/dotnet/Audio.UI.Blazor/Components/AudioRecorder/opus-media-recorder.ts
- src/dotnet/Audio.UI.Blazor/Components/AudioRecorder/workers/opus-encoder-worker.ts
- src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/chat-message-editor.css
- src/dotnet/Chat.UI.Blazor/Components/ChatRecorderToggle.razor
- src/dotnet/Chat.UI.Blazor/Components/MobileControlPanel/MobileRecorderToggle.razor
- src/dotnet/Chat.UI.Blazor/Components/MobileControlPanel/mobile-control-panel.css
- src/dotnet/Chat.UI.Blazor/Services/ChatUI.cs
- src/dotnet/Chat.UI.Blazor/Services/ChatUIStateSync.cs
- src/nodejs/tailwind.config.js
> intermediate recording state

- src/dotnet/UI.Blazor/Components/ContextMenuEx/context-menu.ts
> fix: submit buttons on forms don't work

- src/dotnet/Chat.UI.Blazor/Components/ChatListItem.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/ChatMessage.razor
- src/dotnet/Chat.UI.Blazor/Components/ContactListItem.razor
- src/dotnet/UI.Blazor/Components/Menu/menu-host.ts
> fix: right click menu overflow

- src/dotnet/Chat.UI.Blazor/Components/ChatView/MessageMenu/MessageMenuContent.razor
- src/dotnet/Chat.UI.Blazor/Components/MarkupEditor/markup-editor.ts
- src/dotnet/UI.Blazor/Components/Menu/MenuEntry.razor
> feat: open editor on Edit and Reply on mobiles

- src/dotnet/UI.Blazor/Components/PicUpload/PicUpload.razor
- src/dotnet/UI.Blazor/Components/PicUpload/pic-upload.css
> fix: avatar picker on mobile has wrong size

- src/dotnet/Chat.UI.Blazor/Components/ChatView/MessageMenu/MessageMenuContent.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatView/MessageMenu/MessageMenuPlay.razor
> feat: add color to buttons

- src/dotnet/UI.Blazor/Components/Menu/MenuHost.razor
- src/dotnet/UI.Blazor/Components/Menu/menu-host.ts
> fix: mobile menu overlay shows before menu

- src/dotnet/UI.Blazor/Components/Avatar/AvatarCircle.razor
> fix: some avatars are broken

- src/dotnet/Chat.UI.Blazor/Components/ChatListItem.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/AuthorList.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/RightPanelChatInfo.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/RightPanelHeader.razor
- src/dotnet/Chat.UI.Blazor/Components/ContactListItem.razor
- src/dotnet/Chat.UI.Blazor/Components/LeftPanel/WideLeftPanel.razor
- src/dotnet/Chat.UI.Blazor/Components/components.css
- src/dotnet/UI.Blazor/Components/TabPanel/tab.css
- src/nodejs/styles/main.css
- src/nodejs/tailwind.config.js
> #585 Adjust fonts according to design

- src/dotnet/Chat.UI.Blazor/Components/ChatSearch.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatSearchBox/ChatSearchBox.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatSearchBox/chat-search-box.css
- src/dotnet/Chat.UI.Blazor/Components/LeftPanel/WideLeftPanel.razor
- src/dotnet/Chat.UI.Blazor/exports.ts
- src/dotnet/UI.Blazor/Components/SearchBox/SearchBox.razor
- src/dotnet/UI.Blazor/Components/SearchBox/search-box.css
- src/dotnet/UI.Blazor/Components/TextInput/TextInput.razor
- src/dotnet/UI.Blazor/Components/TextInput/TextInputOptions.cs
- src/dotnet/UI.Blazor/Components/TextInput/text-input.ts
- src/dotnet/UI.Blazor/exports.ts
> fix: search inputs are laggy 

- src/dotnet/Chat.Service/Module/ChatDbInitializer.Generate.cs
- src/dotnet/Users.Service/Module/UsersDbInitializer.cs
> fix: unable to add a contact to contacts

- src/dotnet/UI.Blazor/Components/TabPanel/TabPanel.razor
> fix: tab title alignment issue

- src/dotnet/Chat.UI.Blazor/Components/ChatSearchBox/ChatSearchBox.razor
- src/dotnet/UI.Blazor/Components/Menu/menu-host.ts
- src/dotnet/UI.Blazor/Components/SearchBox/SearchBox.razor
> feat: remove long tap from desktop

- src/dotnet/UI.Blazor/Components/Menu/menu-host.ts
> feat: don't show context menu in Chrome mobile mode on right click

- src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/MessageReactions/message-reactions.css
- src/dotnet/Chat.UI.Blazor/Components/ChatView/chat-view.css
> fix: reactions positioning issue

- src/dotnet/Chat.UI.Blazor/Components/InviteAuthor.razor
- src/dotnet/UI.Blazor/Components/Avatar/AvatarBadge.razor
> fix: invite users modal is broken

- src/dotnet/Chat.UI.Blazor/Components/MarkupEditor/markup-editor.ts
- src/dotnet/Chat.UI.Blazor/Components/MentionList/MentionList.razor
> fix: cursor jumps before mention after mention an author

- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/ChatSettingsModal.razor
- src/dotnet/Chat.UI.Blazor/Components/InviteAuthor/InviteAuthor.razor
- src/dotnet/Chat.UI.Blazor/Components/InviteAuthor/invite-author-modal.css
- src/dotnet/Chat.UI.Blazor/styles.css
> fix: chat settings is cut

- src/nodejs/styles/main.css
> fix: last message is cut on reply\edit

- src/dotnet/Chat.UI.Blazor/Components/Onboarding/AvatarStep.razor
- src/dotnet/Chat.UI.Blazor/Components/Onboarding/PhoneStep.razor
- src/dotnet/Chat.UI.Blazor/Components/Settings/MyAccount.razor
- src/dotnet/Core/DefaultUserPicture.cs
- src/dotnet/UI.Blazor/Components/ErrorHandling/SignOutBlock.razor
- src/dotnet/Users.Service/AccountsBackend.cs
- src/dotnet/Users.Service/Db/DbUserRepo.cs
- src/dotnet/Users.UI.Blazor/Components/OwnAccountEditorModal.razor
- src/dotnet/Users/AccountFull.cs
> feat: prefill account data from claims

- src/nodejs/src/gestures.ts
> fix: native context menu does not work on inputs and markup editor

- src/dotnet/Chat.Client/ClientDefs.cs
- src/dotnet/Chat.Contracts/IRoles.cs
- src/dotnet/Chat.Service/Controllers/RolesController.cs
- src/dotnet/Chat.Service/Roles.cs
- src/dotnet/Chat.UI.Blazor/Components/ChatRightPanel/RightPanelChatInfo.razor
> feat: show group chat owner 

- src/dotnet/Chat.UI.Blazor/Components/Author/AuthorCircle.razor
- src/dotnet/Chat.UI.Blazor/Components/Author/AuthorName.razor
- src/dotnet/Chat.UI.Blazor/Components/AuthorModal.razor
- src/dotnet/Chat.UI.Blazor/Components/AvatarSelect/AvatarSelectModal.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatFooter.razor
- src/dotnet/UI.Blazor/Components/Avatar/AvatarName.razor
- src/dotnet/UI.Blazor/Components/Modal/modal.css
> feat: It should be possible to change chat author avatar #1033

- src/dotnet/Chat.UI.Blazor/Components/ChatList/ChatListItemSkeleton.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatList/ChatListNavbarWidget.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatList/ChatListSkeleton.razor
- src/dotnet/Chat.UI.Blazor/Components/ChatList/chat-list.css
- src/dotnet/UI.Blazor/Components/AccountDropdown/AccountView.razor
- close splash screen earlier on Android;
- shows skeletons in chat list;
- improved own avatar rendering (renders earlier and avoid height jumping);
> Close #1100 Closesplash screen faster on Android 

- src/dotnet/UI.Blazor.App/Pages/Landing/Landing.razor
- src/dotnet/UI.Blazor.App/Pages/Landing/LandingApp.razor
- src/dotnet/UI.Blazor.App/Pages/Landing/LandingHeader.razor
- src/dotnet/UI.Blazor.App/Pages/Landing/LandingWeb.razor
- src/dotnet/UI.Blazor.App/Pages/Landing/landing.css
> update landing page for windows app
